# NUMPY : Package for multi-dimensional array

In [1]:
import numpy as np

In [2]:
s_list=[6,7,8,9]
np.array(s_list)

array([6, 7, 8, 9])

In [3]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(1,31,5) #start,stop,step

array([ 1,  6, 11, 16, 21, 26])

In [14]:
np.arange(5)  #shift+tab->help box

array([0, 1, 2, 3, 4])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.zeros((2,5),float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# linespace,rand.randn,reshape etc

In [27]:
np.linspace(0,2,5) #its linear spacing
#

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [29]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(3,5)

array([[0.41761444, 0.1927533 , 0.13481244, 0.93763189, 0.83612899],
       [0.61442264, 0.39666528, 0.32865395, 0.05868048, 0.29046666],
       [0.3942674 , 0.93841431, 0.06670551, 0.13447944, 0.36916518]])

In [31]:
arr=np.random.randn(2,4)
arr

array([[-0.82250284, -1.90190928, -0.61048507,  0.28983876],
       [-0.50359589, -0.09870421, -0.01758197, -1.12591224]])

In [32]:
np.random.randint(2,100)

57

In [33]:
np.random.randint(20,56,100)

array([38, 36, 42, 42, 36, 26, 26, 49, 23, 50, 27, 38, 23, 33, 46, 28, 23,
       37, 38, 38, 45, 46, 36, 43, 22, 53, 52, 49, 52, 29, 24, 44, 51, 48,
       38, 30, 27, 49, 35, 30, 50, 30, 42, 49, 38, 53, 32, 50, 49, 21, 34,
       40, 29, 22, 55, 42, 21, 36, 20, 22, 40, 49, 35, 29, 41, 35, 54, 24,
       43, 41, 42, 29, 24, 33, 28, 29, 42, 20, 30, 26, 53, 28, 20, 36, 28,
       51, 32, 53, 20, 35, 39, 37, 31, 37, 29, 22, 47, 53, 42, 32])

In [34]:
a_array=np.arange(30)
a_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
rand_array=np.random.randint(0,100,20)
rand_array

array([39, 44, 74, 81, 82, 91, 99, 60, 64, 36, 60, 40, 33, 39, 37,  0, 99,
        5, 74,  9])

In [40]:
a_array.reshape(5,6) 
#its possible because array sixe is 30

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
a_array.reshape(4,3) 
#not possible as array size is 30

ValueError: cannot reshape array of size 30 into shape (4,3)

In [41]:
rand_array.max()

99

In [42]:
rand_array.argmax()

6

In [44]:
b=np.eye(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
b.T #t-> transpose

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
b=np.random.rand(2,3)
b

array([[0.94185314, 0.40740801, 0.88516779],
       [0.52271713, 0.29548073, 0.27472573]])

In [49]:
b.T #t-> transpose

array([[0.94185314, 0.52271713],
       [0.40740801, 0.29548073],
       [0.88516779, 0.27472573]])

In [51]:
a_array=np.arange(10,21)
a_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
a_array[0]

10

In [53]:
a_array[2:5]

array([12, 13, 14])

In [54]:
a_array[1:4]=100
a_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [55]:
a_array=np.arange(10,21)
a_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
a_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [57]:
subset_a_array=a_array[0:7]
subset_a_array

array([10, 11, 12, 13, 14, 15, 16])

In [58]:
subset_a_array[:]=1001
subset_a_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# TWO-DIMENSIONAL ARRAY

In [64]:
a_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
a_matrix   #row - 0
                 #1
                 #2

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [60]:
a_matrix[1,2]

21

In [61]:
a_matrix[2,:]

array([56, 76, 24,  7])

In [62]:
a_matrix[2]

array([56, 76, 24,  7])

In [65]:
a_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# SELECTION TECHNIQUES

# IN NEXT CLASS .......