# selection techniques 

## -->>NUMPY

In [3]:
import numpy as np
a_array=np.arange(1,20)
a_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
a_array+a_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [6]:
np.exp(a_array) #expotential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.sqrt(a_array) #square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [8]:
np.log(a_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [9]:
np.max(a_array) #max

19

In [10]:
np.min(a_array) #min

1

In [18]:
np.argmax(a_array) #index of max value

18

In [19]:
np.argmin(a_array)  #index of min value

0

In [20]:
np.square(a_array) 
#square of every element in array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [21]:
np.std(a_array)  #std deviation

5.477225575051661

In [22]:
np.var(a_array) #variance

30.0

In [23]:
np.mean(a_array)

10.0

In [24]:
array=np.random.randn(3,4)
array

array([[-1.25065534,  2.02938031,  0.26663473,  0.00988553],
       [ 1.18155929, -2.04645092, -1.14536042, -0.4142852 ],
       [-0.82332001,  0.41059032,  0.74696503,  1.63813663]])

In [25]:
np.round(array,decimal=2)

TypeError: _around_dispatcher() got an unexpected keyword argument 'decimal'

In [27]:
sports=np.array(['golf','cricket','cricket','football'])
np.unique(sports) #unique prints unique value

array(['cricket', 'football', 'golf'], dtype='<U8')

## -->>PANDAS

In [29]:
import numpy as np
import pandas as pd

In [30]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [31]:
sports1['football']

2

In [32]:
sports2=pd.Series([11,2,3,4],index=["cricket",'football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [33]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [34]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.206112  0.323352  0.565726  0.809144  0.264125
B  0.572841  0.106684  0.164429  0.120675  0.268626
C  0.379933  0.844859  0.437395  0.919823  0.102375
D  0.065239  0.346067  0.197173  0.564673  0.893819
E  0.634783  0.693006  0.240517  0.856362  0.687429
F  0.092787  0.031803  0.508702  0.289817  0.454447
G  0.762422  0.410660  0.692577  0.643664  0.078568
H  0.749529  0.946552  0.909219  0.230899  0.185097

In [35]:
df1["Score1"]

A    0.206112
B    0.572841
C    0.379933
D    0.065239
E    0.634783
F    0.092787
G    0.762422
H    0.749529
Name: Score1, dtype: float64

In [36]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.206112  0.323352  0.565726
B  0.572841  0.106684  0.164429
C  0.379933  0.844859  0.437395
D  0.065239  0.346067  0.197173
E  0.634783  0.693006  0.240517
F  0.092787  0.031803  0.508702
G  0.762422  0.410660  0.692577
H  0.749529  0.946552  0.909219

In [37]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.206112  0.323352  0.565726  0.809144  0.264125  0.529465
B  0.572841  0.106684  0.164429  0.120675  0.268626  0.679526
C  0.379933  0.844859  0.437395  0.919823  0.102375  1.224792
D  0.065239  0.346067  0.197173  0.564673  0.893819  0.411306
E  0.634783  0.693006  0.240517  0.856362  0.687429  1.327790
F  0.092787  0.031803  0.508702  0.289817  0.454447  0.124591
G  0.762422  0.410660  0.692577  0.643664  0.078568  1.173082
H  0.749529  0.946552  0.909219  0.230899  0.185097  1.696081

In [47]:
df2={'ID':['101','102','103','104','105'],'NAME':['john','meery','aka','kevin','lolly'],'PROFIT':[20,54,89,15,321]}
df=pd.DataFrame(df2)
df

ID   NAME  PROFIT
0  101   john      20
1  102  meery      54
2  103    aka      89
3  104  kevin      15
4  105  lolly     321

In [39]:
df["ID"]

0    101
1    102
2    103
3    104
4    105
Name: ID, dtype: object

In [40]:
df[["ID","NAME","PROFIT"]]

ID   NAME  PROFIT
0  101   john      20
1  102  meery      54
2  103    aka      89
3  104  kevin      15
4  105  lolly     321

In [48]:
df=df.drop("ID",axis=1)

In [49]:
df.drop(3)

NAME  PROFIT
0   john      20
1  meery      54
2    aka      89
4  lolly     321

In [50]:
df

NAME  PROFIT
0   john      20
1  meery      54
2    aka      89
3  kevin      15
4  lolly     321